#!/usr/bin/bash
export LC_COLLATE=C
shopt -s extglob
mkdir -p database
cd database
select i in CreateDB ConnectDB ListDB DropDB
do 
case $i in 
CreateDB )
. ./createDB.sh
break
;;
ConnectDB )
. ./connectDB.sh
break
;;
ListDB ) 
. ./listDB
break
;;
DropDB )
. ./dropDB
break
;;
esac
done
